server:
  port: 8081
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:config/server-keystore.p12
    key-store-password: server
    key-alias: server

spring:
  application:
    name: jsec

logging:
  level:
    org.springframework.boot.autoconfigure.logging: ERROR

management.endpoint.info.enabled: true
management.endpoints.web.exposure.include: health,metrics,prometheus,loggers